<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'phpsolr\\client' => '/Client.php',
                'phpsolr\\configuration' => '/Configuration.php',
                'phpsolr\\configurationexception' => '/ConfigurationException.php',
                'phpsolr\\curl' => '/Curl.php',
                'phpsolr\\exception' => '/Exception.php',
                'phpsolr\\map' => '/Map.php',
                'phpsolr\\mapexception' => '/MapException.php',
                'phpsolr\\queries\\dismax' => '/Query/DisMax.php',
                'phpsolr\\queries\\facets\\abstractfield' => '/Query/Facets/AbstractField.php',
                'phpsolr\\queries\\facets\\facets' => '/Query/Facets/Facets.php',
                'phpsolr\\queries\\facets\\field' => '/Query/Facets/Field.php',
                'phpsolr\\queries\\facets\\query' => '/Query/Facets/Query.php',
                'phpsolr\\queries\\query' => '/Query/Query.php',
                'phpsolr\\queries\\stats\\field' => '/Query/Stats/Field.php',
                'phpsolr\\queries\\stats\\stats' => '/Query/Stats/Stats.php',
                'phpsolr\\queryexception' => '/Query/QueryException.php',
                'phpsolr\\request' => '/Request.php',
                'phpsolr\\responses\\abstractresponse' => '/Responses/AbstractResponse.php',
                'phpsolr\\responses\\errorinterface' => '/Responses/ErrorInterface.php',
                'phpsolr\\responses\\json\\abstractresponsefield' => '/Responses/Json/AbstractResponseField.php',
                'phpsolr\\responses\\json\\error' => '/Responses/Json/Error.php',
                'phpsolr\\responses\\json\\facetcounts' => '/Responses/Json/FacetCounts.php',
                'phpsolr\\responses\\json\\facetfield' => '/Responses/Json/FacetField.php',
                'phpsolr\\responses\\json\\responseheader' => '/Responses/Json/ResponseHeader.php',
                'phpsolr\\responses\\json\\value' => '/Responses/Json/Value.php',
                'phpsolr\\responses\\jsonresponse' => '/Responses/JsonResponse.php',
                'phpsolr\\responses\\responseexception' => '/Responses/ResponseException.php',
                'phpsolr\\responses\\responseheaderinterface' => '/Responses/ResponseHeaderInterface.php',
                'phpsolr\\spellcheck' => '/SpellCheck.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
